In [1]:
from numpy import *
import numpy as np
from sklearn import *
import pandas as pd

In [3]:
train_df=pd.read_excel('C:/Users/shrut/Desktop/Pragyan/Datasets.xlsx',sheet_name='Train')
train_df

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (Class label)
0,Female,17,7,5,7,7,2,dependable
1,Female,20,6,5,4,5,5,serious
2,Male,19,3,5,3,4,2,dependable
3,Female,17,6,7,6,6,6,extraverted
4,Female,18,7,5,6,6,4,serious
...,...,...,...,...,...,...,...,...
704,Female,26,4,7,5,7,3,extraverted
705,Male,20,5,3,6,7,6,responsible
706,Male,18,6,2,7,6,6,dependable
707,Male,19,2,2,6,4,6,extraverted
708,Female,21,5,3,4,5,6,dependable

In [4]:
test_df=pd.read_excel('C:/Users/shrut/Desktop/Pragyan/Datasets.xlsx',sheet_name='Test')
test_df

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (Class label)
0,Male,23,5,7,1,3,6,extraverted
1,Male,17,6,5,6,2,7,serious
2,Male,19,5,5,5,4,3,serious
3,Female,24,2,6,7,4,6,serious
4,Male,24,4,5,5,6,2,lively
...,...,...,...,...,...,...,...,...
310,Male,17,7,5,7,5,1,lively
311,Male,20,3,4,6,6,5,serious
312,Female,18,5,5,5,7,4,extraverted
313,Male,24,5,6,7,4,5,serious
314,Female,19,6,6,6,5,5,extraverted

In [5]:
train_array=train_df.values
train_array

array([['Female', 17, 7, ..., 7, 2, 'dependable'],
       ['Female', 20, 6, ..., 5, 5, 'serious'],
       ['Male', 19, 3, ..., 4, 2, 'dependable'],
       ...,
       ['Male', 18, 6, ..., 6, 6, 'dependable'],
       ['Male', 19, 2, ..., 4, 6, 'extraverted'],
       ['Female', 21, 5, ..., 5, 6, 'dependable']], dtype=object)

In [6]:
test_array=test_df.values
test_array

array([['Male', 23, 5, ..., 3, 6, 'extraverted'],
       ['Male', 17, 6, ..., 2, 7, 'serious'],
       ['Male', 19, 5, ..., 4, 3, 'serious'],
       ...,
       ['Female', 18, 5, ..., 7, 4, 'extraverted'],
       ['Male', 24, 5, ..., 4, 5, 'serious'],
       ['Female', 19, 6, ..., 5, 5, 'extraverted']], dtype=object)

In [7]:
for i in range(len(train_array)):
    if train_array[i][0]=="Male":
        train_array[i][0]=0
    else:
        train_array[i][0]=1

In [8]:
train_array

array([[1, 17, 7, ..., 7, 2, 'dependable'],
       [1, 20, 6, ..., 5, 5, 'serious'],
       [0, 19, 3, ..., 4, 2, 'dependable'],
       ...,
       [0, 18, 6, ..., 6, 6, 'dependable'],
       [0, 19, 2, ..., 4, 6, 'extraverted'],
       [1, 21, 5, ..., 5, 6, 'dependable']], dtype=object)

In [9]:
for i in range(len(test_array)):
    if test_array[i][0]=="Male":
        test_array[i][0]=0
    else:
        test_array[i][0]=1

In [10]:
test_array

array([[0, 23, 5, ..., 3, 6, 'extraverted'],
       [0, 17, 6, ..., 2, 7, 'serious'],
       [0, 19, 5, ..., 4, 3, 'serious'],
       ...,
       [1, 18, 5, ..., 7, 4, 'extraverted'],
       [0, 24, 5, ..., 4, 5, 'serious'],
       [1, 19, 6, ..., 5, 5, 'extraverted']], dtype=object)

In [11]:
training_df=pd.DataFrame(train_array)
testing_df=pd.DataFrame(test_array)

In [12]:
training_df

     0   1  2  3  4  5  6            7
0    1  17  7  5  7  7  2   dependable
1    1  20  6  5  4  5  5      serious
2    0  19  3  5  3  4  2   dependable
3    1  17  6  7  6  6  6  extraverted
4    1  18  7  5  6  6  4      serious
..  ..  .. .. .. .. .. ..          ...
704  1  26  4  7  5  7  3  extraverted
705  0  20  5  3  6  7  6  responsible
706  0  18  6  2  7  6  6   dependable
707  0  19  2  2  6  4  6  extraverted
708  1  21  5  3  4  5  6   dependable

[709 rows x 8 columns]

In [13]:
testing_df

     0   1  2  3  4  5  6            7
0    0  23  5  7  1  3  6  extraverted
1    0  17  6  5  6  2  7      serious
2    0  19  5  5  5  4  3      serious
3    1  24  2  6  7  4  6      serious
4    0  24  4  5  5  6  2       lively
..  ..  .. .. .. .. .. ..          ...
310  0  17  7  5  7  5  1       lively
311  0  20  3  4  6  6  5      serious
312  1  18  5  5  5  7  4  extraverted
313  0  24  5  6  7  4  5      serious
314  1  19  6  6  6  5  5  extraverted

[315 rows x 8 columns]

In [14]:
train_input_array=training_df[[0,1,2,3,4,5,6]].values
train_input_array

array([[1, 17, 7, ..., 7, 7, 2],
       [1, 20, 6, ..., 4, 5, 5],
       [0, 19, 3, ..., 3, 4, 2],
       ...,
       [0, 18, 6, ..., 7, 6, 6],
       [0, 19, 2, ..., 6, 4, 6],
       [1, 21, 5, ..., 4, 5, 6]], dtype=object)

In [15]:
test_input_array=testing_df[[0,1,2,3,4,5,6]].values
test_input_array

array([[0, 23, 5, ..., 1, 3, 6],
       [0, 17, 6, ..., 6, 2, 7],
       [0, 19, 5, ..., 5, 4, 3],
       ...,
       [1, 18, 5, ..., 5, 7, 4],
       [0, 24, 5, ..., 7, 4, 5],
       [1, 19, 6, ..., 6, 5, 5]], dtype=object)

In [16]:
train_output_array=training_df[7].values
train_output_array

array(['dependable', 'serious', 'dependable', 'extraverted', 'serious',
       'extraverted', 'dependable', 'dependable', 'responsible',
       'serious', 'lively', 'lively', 'extraverted', 'extraverted',
       'serious', 'extraverted', 'lively', 'lively', 'extraverted',
       'dependable', 'lively', 'lively', 'responsible', 'extraverted',
       'responsible', 'dependable', 'serious', 'serious', 'responsible',
       'dependable', 'responsible', 'dependable', 'extraverted',
       'extraverted', 'responsible', 'dependable', 'responsible',
       'serious', 'extraverted', 'dependable', 'lively', 'lively',
       'extraverted', 'lively', 'serious', 'responsible', 'extraverted',
       'serious', 'dependable', 'serious', 'dependable', 'responsible',
       'dependable', 'extraverted', 'extraverted', 'serious', 'lively',
       'responsible', 'dependable', 'lively', 'serious', 'responsible',
       'responsible', 'lively', 'dependable', 'dependable', 'lively',
       'extraverted', 'responsible', 'lively', 'extraverted',
       'dependable', 'serious', 'serious', 'lively', 'lively',
       'extraverted', 'responsible', 'dependable', 'dependable',
       'responsible', 'dependable', 'responsible', 'serious', 'serious',
       'lively', 'serious', 'extraverted', 'serious', 'extraverted',
       'responsible', 'responsible', 'lively', 'extraverted',
       'responsible', 'serious', 'responsible', 'serious', 'serious',
       'extraverted', 'extraverted', 'dependable', 'dependable', 'lively',
       'lively', 'dependable', 'responsible', 'serious', 'serious',
       'serious', 'extraverted', 'serious', 'extraverted', 'dependable',
       'responsible', 'lively', 'extraverted', 'dependable', 'serious',
       'responsible', 'extraverted', 'lively', 'serious', 'extraverted',
       'dependable', 'dependable', 'dependable', 'responsible',
       'dependable', 'responsible', 'lively', 'responsible', 'lively',
       'extraverted', 'extraverted', 'responsible', 'serious',
       'extraverted', 'lively', 'extraverted', 'extraverted', 'serious',
       'serious', 'serious', 'responsible', 'serious', 'extraverted',
       'lively', 'lively', 'extraverted', 'serious', 'dependable',
       'serious', 'lively', 'responsible', 'lively', 'serious',
       'extraverted', 'extraverted', 'responsible', 'lively',
       'extraverted', 'serious', 'dependable', 'extraverted', 'lively',
       'lively', 'extraverted', 'extraverted', 'dependable', 'lively',
       'serious', 'extraverted', 'lively', 'dependable', 'responsible',
       'extraverted', 'serious', 'dependable', 'responsible',
       'extraverted', 'responsible', 'extraverted', 'responsible',
       'serious', 'serious', 'dependable', 'extraverted', 'extraverted',
       'lively', 'lively', 'extraverted', 'extraverted', 'dependable',
       'lively', 'serious', 'lively', 'responsible', 'responsible',
       'serious', 'responsible', 'serious', 'extraverted', 'extraverted',
       'serious', 'serious', 'lively', 'responsible', 'dependable',
       'serious', 'lively', 'dependable', 'lively', 'extraverted',
       'dependable', 'dependable', 'serious', 'lively', 'lively',
       'extraverted', 'serious', 'lively', 'lively', 'serious',
       'extraverted', 'serious', 'dependable', 'extraverted',
       'extraverted', 'serious', 'responsible', 'responsible',
       'extraverted', 'responsible', 'serious', 'responsible',
       'extraverted', 'serious', 'serious', 'responsible', 'extraverted',
       'lively', 'dependable', 'extraverted', 'extraverted', 'dependable',
       'lively', 'extraverted', 'lively', 'responsible', 'dependable',
       'dependable', 'serious', 'responsible', 'extraverted', 'lively',
       'extraverted', 'dependable', 'serious', 'responsible', 'serious',
       'lively', 'lively', 'responsible', 'extraverted', 'serious',
       'extraverted', 'lively', 'serious', 'extraverted', 'dependable',
       'lively', 'lively', 'serious', 'extraverted', 'responsible',
       'dependable', 'lively', 'serious', 'responsible', 'dependable',
       'lively', 'dependable', 'extraverted', 'extraverted', 'lively',
       'dependable', 'responsible', 'serious', 'extraverted',
       'dependable', 'lively', 'lively', 'responsible', 'lively',
       'serious', 'responsible', 'lively', 'serious', 'dependable',
       'serious', 'lively', 'responsible', 'dependable', 'extraverted',
       'dependable', 'serious', 'lively', 'responsible', 'extraverted',
       'lively', 'serious', 'responsible', 'responsible', 'lively',
       'serious', 'dependable', 'lively', 'extraverted', 'serious',
       'lively', 'extraverted', 'dependable', 'responsible', 'serious',
       'lively', 'lively', 'dependable', 'responsible', 'dependable',
       'dependable', 'lively', 'dependable', 'responsible', 'serious',
       'dependable', 'lively', 'serious', 'extraverted', 'lively',
       'extraverted', 'responsible', 'responsible', 'dependable',
       'extraverted', 'responsible', 'serious', 'lively', 'serious',
       'serious', 'extraverted', 'serious', 'dependable', 'dependable',
       'lively', 'extraverted', 'dependable', 'responsible', 'serious',
       'lively', 'serious', 'extraverted', 'serious', 'serious',
       'dependable', 'responsible', 'serious', 'extraverted',
       'dependable', 'serious', 'dependable', 'extraverted', 'lively',
       'serious', 'responsible', 'dependable', 'lively', 'dependable',
       'serious', 'dependable', 'responsible', 'lively', 'dependable',
       'lively', 'extraverted', 'extraverted', 'lively', 'serious',
       'extraverted', 'lively', 'dependable', 'extraverted', 'serious',
       'serious', 'dependable', 'responsible', 'serious', 'extraverted',
       'serious', 'lively', 'extraverted', 'serious', 'responsible',
       'serious', 'lively', 'responsible', 'dependable', 'serious',
       'extraverted', 'extraverted', 'extraverted', 'dependable',
       'responsible', 'serious', 'responsible', 'dependable',
       'responsible', 'serious', 'dependable', 'serious', 'lively',
       'extraverted', 'serious', 'dependable', 'serious', 'lively',
       'extraverted', 'lively', 'responsible', 'responsible',
       'extraverted', 'serious', 'extraverted', 'responsible',
       'responsible', 'responsible', 'dependable', 'dependable',
       'dependable', 'responsible', 'serious', 'extraverted', 'serious',
       'lively', 'extraverted', 'extraverted', 'dependable', 'lively',
       'lively', 'serious', 'responsible', 'dependable', 'responsible',
       'extraverted', 'responsible', 'extraverted', 'serious',
       'dependable', 'extraverted', 'extraverted', 'dependable',
       'responsible', 'lively', 'serious', 'serious', 'serious',
       'extraverted', 'dependable', 'responsible', 'dependable', 'lively',
       'responsible', 'lively', 'extraverted', 'serious', 'responsible',
       'responsible', 'dependable', 'dependable', 'serious', 'serious',
       'serious', 'lively', 'serious', 'extraverted', 'responsible',
       'lively', 'dependable', 'serious', 'lively', 'dependable',
       'lively', 'dependable', 'serious', 'extraverted', 'dependable',
       'lively', 'serious', 'extraverted', 'lively', 'lively',
       'extraverted', 'dependable', 'serious', 'extraverted',
       'responsible', 'serious', 'serious', 'responsible', 'lively',
       'serious', 'serious', 'lively', 'serious', 'responsible',
       'dependable', 'dependable', 'lively', 'extraverted', 'extraverted',
       'lively', 'responsible', 'serious', 'serious', 'responsible',
       'dependable', 'serious', 'extraverted', 'dependable',
       'extraverted', 'lively', 'dependable', 'dependable', 'lively',
       'responsible', 'lively', 'serious', 'serious', 'dependable',
       'serious', 'extraverted', 'extraverted', 'lively', 'extraverted',
       'responsible', 'extraverted', 'serious', 'lively', 'serious',
       'serious', 'extraverted', 'extraverted', 'serious', 'dependable',
       'lively', 'lively', 'dependable', 'lively', 'dependable',
       'serious', 'extraverted', 'dependable', 'responsible',
       'dependable', 'serious', 'serious', 'responsible', 'responsible',
       'extraverted', 'dependable', 'lively', 'serious', 'serious',
       'lively', 'responsible', 'responsible', 'extraverted', 'lively',
       'lively', 'extraverted', 'dependable', 'dependable', 'serious',
       'extraverted', 'dependable', 'lively', 'serious', 'extraverted',
       'responsible', 'extraverted', 'extraverted', 'responsible',
       'dependable', 'serious', 'lively', 'serious', 'extraverted',
       'dependable', 'responsible', 'extraverted', 'serious', 'serious',
       'responsible', 'lively', 'responsible', 'serious', 'dependable',
       'dependable', 'serious', 'dependable', 'dependable', 'responsible',
       'lively', 'dependable', 'responsible', 'serious', 'lively',
       'dependable', 'serious', 'lively', 'responsible', 'responsible',
       'extraverted', 'serious', 'lively', 'serious', 'lively',
       'extraverted', 'lively', 'dependable', 'lively', 'dependable',
       'responsible', 'responsible', 'responsible', 'serious',
       'dependable', 'responsible', 'serious', 'serious', 'lively',
       'serious', 'extraverted', 'responsible', 'responsible',
       'extraverted', 'extraverted', 'serious', 'dependable', 'lively',
       'responsible', 'lively', 'extraverted', 'extraverted',
       'dependable', 'responsible', 'extraverted', 'responsible',
       'extraverted', 'extraverted', 'serious', 'lively', 'serious',
       'serious', 'extraverted', 'dependable', 'responsible', 'lively',
       'extraverted', 'responsible', 'extraverted', 'dependable',
       'dependable', 'serious', 'responsible', 'dependable', 'serious',
       'dependable', 'responsible', 'responsible', 'serious', 'lively',
       'extraverted', 'dependable', 'extraverted', 'serious', 'serious',
       'responsible', 'serious', 'serious', 'extraverted', 'extraverted',
       'responsible', 'lively', 'responsible', 'dependable',
       'extraverted', 'dependable', 'dependable', 'dependable',
       'dependable', 'extraverted', 'lively', 'lively', 'extraverted',
       'responsible', 'dependable', 'extraverted', 'dependable'],
      dtype=object)

for i in range(len(train_output_array)):
    train_output_array[i]=str(train_output_array[i])
train_output_array

In [17]:
test_output_array=testing_df[7].values
test_output_array

array(['extraverted', 'serious', 'serious', 'serious', 'lively',
       'extraverted', 'serious', 'extraverted', 'serious', 'serious',
       'serious', 'responsible', 'serious', 'dependable', 'serious',
       'serious', 'responsible', 'serious', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious',
       'responsible', 'extraverted', 'serious', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'extraverted', 'extraverted',
       'serious', 'lively', 'serious', 'serious', 'serious', 'serious',
       'dependable', 'responsible', 'responsible', 'serious', 'serious',
       'serious', 'serious', 'extraverted', 'serious', 'serious',
       'extraverted', 'extraverted', 'extraverted', 'extraverted',
       'dependable', 'serious', 'serious', 'extraverted', 'dependable',
       'serious', 'serious', 'serious', 'lively', 'serious',
       'extraverted', 'extraverted', 'serious', 'serious', 'serious',
       'extraverted', 'lively', 'lively', 'responsible', 'serious',
       'lively', 'serious', 'serious', 'responsible', 'responsible',
       'serious', 'dependable', 'dependable', 'serious', 'serious',
       'dependable', 'responsible', 'responsible', 'extraverted',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'dependable', 'extraverted', 'serious', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'serious', 'responsible',
       'serious', 'extraverted', 'serious', 'serious', 'serious',
       'serious', 'responsible', 'responsible', 'serious', 'lively',
       'extraverted', 'serious', 'serious', 'serious', 'extraverted',
       'serious', 'dependable', 'serious', 'extraverted', 'extraverted',
       'serious', 'extraverted', 'dependable', 'serious', 'responsible',
       'serious', 'lively', 'extraverted', 'lively', 'serious', 'serious',
       'serious', 'serious', 'extraverted', 'serious', 'responsible',
       'responsible', 'serious', 'extraverted', 'dependable', 'serious',
       'responsible', 'dependable', 'serious', 'responsible',
       'extraverted', 'serious', 'responsible', 'serious', 'extraverted',
       'serious', 'lively', 'responsible', 'extraverted', 'lively',
       'serious', 'responsible', 'responsible', 'lively', 'dependable',
       'serious', 'serious', 'serious', 'serious', 'responsible',
       'serious', 'extraverted', 'serious', 'lively', 'serious',
       'responsible', 'responsible', 'serious', 'extraverted', 'serious',
       'serious', 'responsible', 'extraverted', 'responsible',
       'extraverted', 'lively', 'responsible', 'serious', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'extraverted',
       'lively', 'serious', 'extraverted', 'extraverted', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'serious', 'serious', 'extraverted', 'dependable', 'serious',
       'extraverted', 'extraverted', 'responsible', 'dependable',
       'serious', 'serious', 'lively', 'extraverted', 'serious',
       'serious', 'serious', 'extraverted', 'responsible', 'serious',
       'extraverted', 'responsible', 'extraverted', 'extraverted',
       'lively', 'dependable', 'extraverted', 'dependable', 'serious',
       'dependable', 'lively', 'extraverted', 'dependable', 'serious',
       'serious', 'extraverted', 'serious', 'extraverted', 'responsible',
       'serious', 'extraverted', 'serious', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'extraverted', 'serious',
       'serious', 'serious', 'serious', 'extraverted', 'serious',
       'extraverted', 'extraverted', 'serious', 'serious', 'serious',
       'serious', 'lively', 'extraverted', 'extraverted', 'responsible',
       'responsible', 'extraverted', 'serious', 'serious', 'responsible',
       'extraverted', 'serious', 'dependable', 'serious', 'responsible',
       'lively', 'extraverted', 'responsible', 'extraverted', 'serious',
       'serious', 'serious', 'responsible', 'responsible', 'serious',
       'serious', 'lively', 'serious', 'responsible', 'serious', 'lively',
       'serious', 'extraverted', 'extraverted', 'extraverted', 'serious',
       'serious', 'extraverted', 'extraverted', 'serious', 'serious',
       'extraverted', 'lively', 'lively', 'serious', 'extraverted',
       'serious', 'extraverted'], dtype=object)

for i in range(len(test_output_array)):
    test_output_array[i] =str(test_output_array[i])
test_output_array

In [18]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)
mul_lr.fit(train_input_array,train_output_array)

LogisticRegression(max_iter=1000, multi_class='multinomial', solver='newton-cg')

In [19]:
y_pred= mul_lr.predict(test_input_array)
for i in range(len(y_pred)) :
    y_pred[i]=str((y_pred[i]))
y_pred

array(['extraverted', 'serious', 'serious', 'serious', 'lively',
       'extraverted', 'serious', 'extraverted', 'serious', 'serious',
       'serious', 'responsible', 'serious', 'dependable', 'serious',
       'serious', 'responsible', 'serious', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious',
       'responsible', 'extraverted', 'serious', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'extraverted', 'extraverted',
       'serious', 'lively', 'serious', 'serious', 'serious', 'serious',
       'serious', 'responsible', 'serious', 'serious', 'serious',
       'serious', 'serious', 'extraverted', 'serious', 'serious',
       'extraverted', 'extraverted', 'extraverted', 'extraverted',
       'serious', 'serious', 'serious', 'extraverted', 'serious',
       'serious', 'serious', 'serious', 'lively', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'serious', 'extraverted',
       'lively', 'lively', 'serious', 'serious', 'lively', 'serious',
       'serious', 'serious', 'responsible', 'serious', 'serious',
       'dependable', 'serious', 'serious', 'dependable', 'serious',
       'responsible', 'extraverted', 'serious', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'extraverted',
       'serious', 'serious', 'serious', 'dependable', 'serious',
       'serious', 'serious', 'responsible', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'responsible',
       'responsible', 'serious', 'lively', 'extraverted', 'serious',
       'serious', 'serious', 'extraverted', 'serious', 'extraverted',
       'serious', 'extraverted', 'serious', 'serious', 'extraverted',
       'extraverted', 'serious', 'responsible', 'serious', 'lively',
       'extraverted', 'lively', 'serious', 'serious', 'serious',
       'serious', 'extraverted', 'serious', 'responsible', 'responsible',
       'serious', 'lively', 'serious', 'serious', 'responsible',
       'dependable', 'serious', 'responsible', 'extraverted', 'serious',
       'extraverted', 'serious', 'extraverted', 'serious', 'responsible',
       'responsible', 'extraverted', 'lively', 'serious', 'responsible',
       'responsible', 'lively', 'serious', 'serious', 'extraverted',
       'serious', 'serious', 'serious', 'serious', 'extraverted',
       'serious', 'extraverted', 'serious', 'responsible', 'responsible',
       'extraverted', 'extraverted', 'serious', 'serious', 'responsible',
       'extraverted', 'serious', 'extraverted', 'lively', 'dependable',
       'serious', 'extraverted', 'extraverted', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'serious',
       'extraverted', 'extraverted', 'extraverted', 'extraverted',
       'extraverted', 'extraverted', 'serious', 'serious', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'serious', 'extraverted', 'serious', 'serious', 'extraverted',
       'extraverted', 'responsible', 'serious', 'serious', 'serious',
       'lively', 'serious', 'serious', 'serious', 'serious',
       'extraverted', 'dependable', 'serious', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'lively', 'serious',
       'extraverted', 'dependable', 'serious', 'dependable',
       'extraverted', 'extraverted', 'extraverted', 'serious', 'serious',
       'extraverted', 'serious', 'extraverted', 'extraverted', 'serious',
       'extraverted', 'serious', 'serious', 'extraverted', 'extraverted',
       'serious', 'serious', 'extraverted', 'serious', 'serious',
       'serious', 'serious', 'extraverted', 'serious', 'serious',
       'extraverted', 'serious', 'serious', 'extraverted', 'serious',
       'lively', 'extraverted', 'extraverted', 'serious', 'responsible',
       'extraverted', 'serious', 'extraverted', 'responsible',
       'extraverted', 'serious', 'serious', 'serious', 'responsible',
       'serious', 'extraverted', 'extraverted', 'extraverted', 'serious',
       'serious', 'serious', 'responsible', 'responsible', 'serious',
       'serious', 'lively', 'serious', 'serious', 'serious', 'lively',
       'serious', 'extraverted', 'extraverted', 'extraverted', 'serious',
       'serious', 'extraverted', 'extraverted', 'serious', 'serious',
       'extraverted', 'serious', 'lively', 'serious', 'extraverted',
       'serious', 'extraverted'], dtype=object)

In [20]:
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])
DF.index=DF.index+1
DF.index.names = ['Person No']
DF.to_csv("output.csv")

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
accuracy_score(y_pred,test_output_array)*100

85.39682539682539

In [23]:
confusion_matrix(y_pred,test_output_array)

array([[  6,   1,   0,   2,   0],
       [  3,  71,   3,   4,   5],
       [  0,   1,  18,   0,   0],
       [  0,   0,   1,  26,   0],
       [ 11,   5,   2,   8, 148]], dtype=int64)

In [24]:
classification_report(y_pred,test_output_array)

'              precision    recall  f1-score   support\n\n  dependable       0.30      0.67      0.41         9\n extraverted       0.91      0.83      0.87        86\n      lively       0.75      0.95      0.84        19\n responsible       0.65      0.96      0.78        27\n     serious       0.97      0.85      0.91       174\n\n    accuracy                           0.85       315\n   macro avg       0.72      0.85      0.76       315\nweighted avg       0.89      0.85      0.87       315\n'